/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Recetas;

import Base_datos.Conectar_Mysql;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author oscar_o31
 */
public class Recetas extends javax.swing.JFrame {

    /**
     * Creates new form Recetas
     */
    
    int a=0, b=0, fila1, copa, come, idpa = 0, idme = 0;
    public Recetas() {
        initComponents();
        
        int a1=0;
        
        try{
            
            DefaultTableModel model = new DefaultTableModel();
            jtConsulta.setModel(model);
            model.setColumnIdentifiers(new Object[]{"Codigo del Paciente", "Nombre", "Apellido", "Edad", "Sexo", "Cedula", "Telefono", "Fecha de nacimiento", "Seguro", "Fecha del regristro"});
            
            
            ResultSet rs = bd.Vertodo("select * from recetas");
            ResultSet rst = bd.Vertodo("select * from Pacientes");
            
            
            while(rs.next()){
            a1 = rs.getInt("Id_receta");
                
            }
            while(rst.next()){

                model.addRow(new Object[]{rst.getInt("Id_pacientes"), rst.getString("Nombre_pa"), rst.getString("Apellido"), rst.getString("Edad"), rst.getString("Sexo"), rst.getString("Cedula"), rst.getString("Telefono"), rst.getString("Fecha_nacimiento"), rst.getString("Seguro"), rst.getString("Fecha_registro")});

            }
            
            a = a1 + 1;
            
        } catch(Exception e){
            
        } finally{
            bd.close();
        }
        
        jLabel3.setText(String.valueOf(a));
        jLabel8.setText(fecha());
    }

    public void Buscar(){
        DefaultTableModel modelo=(DefaultTableModel) jTable1.getModel();    
            int a1=0;

            
            
        try {
            ResultSet rs1 = bd.Vertodo("select * from recetas");
            while(rs1.next()){
                a1 = rs1.getInt("Id_receta");
                
            }
        } catch (SQLException ex) {
        }
        
        a = a1 + 1;
        jLabel3.setText(String.valueOf(a));
        modelo.addRow(new Object[]{"", "", ""});
        
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdPaciente = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jbtBuscar = new javax.swing.JButton();
        jrbNombre = new javax.swing.JRadioButton();
        jtxtBuscar = new javax.swing.JTextField();
        jrbCodigo = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtConsulta = new javax.swing.JTable();
        jbtMostrar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();

        jdPaciente.setTitle("Consulta Pacientes");
        jdPaciente.setMinimumSize(new java.awt.Dimension(950, 690));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Volver 1.png"))); // NOI18N
        jButton6.setText("Volver");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(672, 612, 140, 50));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel12.setText("Consultar Pacientes");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jbtBuscar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jbtBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        jbtBuscar.setText("Buscar");
        jbtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 160, 50));

        jrbNombre.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jrbNombre.setText("Nombre");
        jPanel2.add(jrbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, -1, -1));
        jPanel2.add(jtxtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 109, 210, 30));

        jrbCodigo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jrbCodigo.setSelected(true);
        jrbCodigo.setText("Codigo");
        jPanel2.add(jrbCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, -1, -1));

        jtConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtConsulta);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 819, -1));

        jbtMostrar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jbtMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mostrar.png"))); // NOI18N
        jbtMostrar.setText("Mostrar Todo");
        jbtMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtMostrarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 240, 50));

        jButton5.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Confirmar.png"))); // NOI18N
        jButton5.setText("Seleccionar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 180, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/textura.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 690));

        javax.swing.GroupLayout jdPacienteLayout = new javax.swing.GroupLayout(jdPaciente.getContentPane());
        jdPaciente.getContentPane().setLayout(jdPacienteLayout);
        jdPacienteLayout.setHorizontalGroup(
            jdPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jdPacienteLayout.setVerticalGroup(
            jdPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Registrar Recetas");
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jLabel1.setText("Registrar Recetas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel2.setText("No. Recetas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 64, 40));

        jLabel5.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel5.setText("Doctor:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel7.setText("Fecha:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, -1));

        jButton1.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        jButton1.setText("Paciente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 144, 26));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 162, 38));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 162, 31));

        jButton3.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar.png"))); // NOI18N
        jButton3.setText("Guardar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, -1, -1));

        jButton4.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cerrar.png"))); // NOI18N
        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Cantidad", "Medicamento", "Docis"
            }
        ));
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 540, 230));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/textura.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Metodo par ala fecha
    public static String fecha(){
        
        Date fecha = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/YYYY");
        
        return formato.format(fecha);
        
    }
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.hide();
    }//GEN-LAST:event_jButton4ActionPerformed

    //Boton para insertar el registro
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        DefaultTableModel modelo=(DefaultTableModel) jTable1.getModel();
        int filas=jTable1.getRowCount();
        
        try{
        
        fila1 = jTable1.getRowCount();
        int j = fila1;
        String Codigo = String.valueOf(a);
        String Medicamento = "";
        String nombrepa = jLabel9.getText();
        String nombreme = jLabel10.getText();
        String docis = "";
        String Cantidad = "";
        String cod = Codigo;
        String nombre = jLabel9.getText();
        
        
        SimpleDateFormat formato = new SimpleDateFormat("YYYY/MM/dd");
        
        Calendar calendario = GregorianCalendar.getInstance();
        Date fecha = calendario.getTime();
        String fechana = "";
        fechana = formato.format(fecha);
        if(fechana.equals("")){
            JOptionPane.showMessageDialog(null, "Faltan datos por introducir!os", "Sistema De Consultorio", JOptionPane.INFORMATION_MESSAGE);
        } else {
        
        if(nombrepa.equals("")){
        
            JOptionPane.showMessageDialog(null, "Faltan datos por introducir!", "Sistema De Consultorio", JOptionPane.INFORMATION_MESSAGE);
            
        }else{
                
                try{
                    
                    if(j==-1){
                        JOptionPane.showMessageDialog(null, "Debe de seleccionar un registro", "Advertencia", JOptionPane.WARNING_MESSAGE);
                    } else {
                        
                            if(jTable1.getValueAt(0,0)==null ){
                                
                                JOptionPane.showMessageDialog(null, "No escrito datos en la receta", "Sistema De Consultorio", JOptionPane.INFORMATION_MESSAGE);
                               
                                
                         } else{
                                try{
                                bd.Insert("insert into recetas(id_receta, nombre_pa, nombre_me, fecha_registro)"
                                   + "values ("+Codigo+", '"+nombrepa+"', '"+nombreme+"', '"+fechana+"')");
                                for(int i = 0;j>i;i++){
                                Cantidad = jTable1.getValueAt(i, 0).toString();
                                Medicamento = jTable1.getValueAt(i, 1).toString();
                                docis = jTable1.getValueAt(i, 2).toString();
                                
                                bd.Insert("insert into recetapa(id_recetapa, Nombre_medicamento, docis, cantidad, Nombre)"
                                + "values ("+cod+",'"+Medicamento+"', '"+docis+"', '"+Cantidad+"', '"+nombre+"')");
                                }
                                for (int i = 0;filas>i; i++) {
                                        modelo.removeRow(0);
                                        
                                }
                                
                                jTable1.removeAll();
                                
                                jLabel9.setText("");
                                Buscar();
                                } catch(Exception e){
                                    JOptionPane.showMessageDialog(null, "Error al insertar datos!", "Sistema De Consultorio", JOptionPane.INFORMATION_MESSAGE);
                                    bd.Insert("delete from recetas where id_receta = "+Codigo+"");
                                    
                                }
                     
                            }
                        }
                    
                    }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "No Se Agrego El Registro ", "Sistema De Consultorio", JOptionPane.INFORMATION_MESSAGE);
                    } finally{
                        bd.close();
                    }
            }
        
            } 
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Faltan datos por introducir!", "Sistema De Consultorio", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        jdPaciente.hide();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jbtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBuscarActionPerformed

        String nombre = jtxtBuscar.getText();

        if(jrbNombre.isSelected() == false && jrbCodigo.isSelected() == false){
            JOptionPane.showMessageDialog(null, "No a elegino ningun tipo a buscar", "Sistema De Consultorio", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if(jrbNombre.isSelected() == true && jrbCodigo.isSelected() == true){
                JOptionPane.showMessageDialog(null, "Solo puede sellecionar una sola opcion", "Sistema De Consultorio", JOptionPane.INFORMATION_MESSAGE);
            } else if(jrbNombre.isSelected() == true){if(nombre.equals("")){
                JOptionPane.showMessageDialog(null, "No a escrito el nombre a buscar", "Sistema De Consultorio", JOptionPane.INFORMATION_MESSAGE);
            } else{
                char k = nombre.charAt(0);
                if(Character.isDigit(k)){
                    JOptionPane.showMessageDialog(null, "Solo Puede introducir Letras", "Sistema De Consultorio", JOptionPane.INFORMATION_MESSAGE);
                } else{

                    try{

                        ResultSet rs = bd.Vertodo("select * from Pacientes where Nombre like'"+nombre+"%'");
                        DefaultTableModel model = new DefaultTableModel();
                        jtConsulta.setModel(model);
                        model.setColumnIdentifiers(new Object[]{"Codigo del Paciente", "Nombre", "Apellido", "Edad", "Sexo", "Cedula", "Telefono", "Fecha de nacimiento", "Seguro", "Fecha del regristro"});

                        while(rs.next()){

                            model.addRow(new Object[]{rs.getInt("Id_pacientes"), rs.getString("Nombre_pa"), rs.getString("Apellido"), rs.getString("Edad"), rs.getString("Sexo"), rs.getString("Cedula"), rs.getString("Telefono"), rs.getString("Fecha_nacimiento"), rs.getString("Seguro"), rs.getString("Fecha_registro")});

                        }

                    } catch(Exception e){

                    } finally{
                        bd.close();
                    }
                }
            }
        }else{
            if(nombre.equals("")){
                JOptionPane.showMessageDialog(null, "No a escrito el codigo a buscar", "Sistema De Consultorio", JOptionPane.INFORMATION_MESSAGE);
            } else {
                try{
                    int ho = Integer.parseInt(nombre);
                    if(ho > 0){
                        ResultSet rs = bd.Vertodo("select * from Pacientes where Id_pacientes = "+nombre+"");
                        DefaultTableModel model = new DefaultTableModel();
                        jtConsulta.setModel(model);
                        model.setColumnIdentifiers(new Object[]{"Codigo del Paciente", "Nombre", "Apellido", "Edad", "Sexo", "Cedula", "Telefono", "Fecha de nacimiento", "Seguro", "Fecha del regristro"});

                        while(rs.next()){

                            model.addRow(new Object[]{rs.getInt("Id_pacientes"), rs.getString("Nombre_pa"), rs.getString("Apellido"), rs.getString("Edad"), rs.getString("Sexo"), rs.getString("Cedula"), rs.getString("Telefono"), rs.getString("Fecha_nacimiento"), rs.getString("Seguro"), rs.getString("Fecha_registro")});

                        }
                    }

                } catch(Exception e){

                    JOptionPane.showMessageDialog(null, "Solo puede introducir numeros", "Sistema De Consultorio", JOptionPane.INFORMATION_MESSAGE);

                } finally{
                    bd.close();
                }
            }
        }
        }
    }//GEN-LAST:event_jbtBuscarActionPerformed

    private void jbtMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtMostrarActionPerformed

        DefaultTableModel model = new DefaultTableModel();
        jtConsulta.setModel(model);
        model.setColumnIdentifiers(new Object[]{"Codigo del Paciente", "Nombre", "Apellido", "Edad", "Sexo", "Cedula", "Telefono", "Fecha de nacimiento", "Seguro", "Fecha del regristro"});
        try{
            ResultSet rs = bd.Vertodo("select * from Pacientes");

            while(rs.next()){

                model.addRow(new Object[]{rs.getInt("Id_pacientes"), rs.getString("Nombre_pa"), rs.getString("Apellido"), rs.getString("Edad"), rs.getString("Sexo"), rs.getString("Cedula"), rs.getString("Telefono"), rs.getString("Fecha_nacimiento"), rs.getString("Seguro"), rs.getString("Fecha_registro")});

            }

        } catch(Exception e){

        } finally{
            bd.close();
        }
    }//GEN-LAST:event_jbtMostrarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        fila1 = jtConsulta.getSelectedRow();
        String at = "";

        try{
            if(fila1==-1){
                JOptionPane.showMessageDialog(null, "Debe de seleccionar un registro", "Advertencia", JOptionPane.WARNING_MESSAGE);
            } else {
                at = jtConsulta.getValueAt(fila1, 1).toString();
                jdPaciente.hide();
                
            }
            this.copa = 1;
            jLabel9.setText(at);

        }catch (Exception ex) {

        }

        fila1 = 0;

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        jdPaciente.show();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        model.addRow(new Object[]{"", "", ""});
        }
        
    }//GEN-LAST:event_jTable1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recetas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtBuscar;
    private javax.swing.JButton jbtMostrar;
    private javax.swing.JDialog jdPaciente;
    private javax.swing.JRadioButton jrbCodigo;
    private javax.swing.JRadioButton jrbNombre;
    private javax.swing.JTable jtConsulta;
    public static javax.swing.JTextField jtxtBuscar;
    // End of variables declaration//GEN-END:variables

    Conectar_Mysql bd = new Conectar_Mysql();

}
