/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pacientesingre;

import Base_datos.Conectar_Mysql;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author oscar_o31
 */
public class Pacientesingre extends javax.swing.JFrame {

    /**
     * Creates new form Pacientesingre
     */
    
    int a=0, b=0, fila1, copa, come, idpa = 0, idme = 0, cotra = 0, idtra = 0;
    
    public Pacientesingre() {
        initComponents();
        
        int a1=0;
        
        try{
            
            ResultSet rs = bd.Vertodo("select * from Pacientes_ingresados");
            ResultSet rst = bd.Vertodo("select * from Pacientes");
            ResultSet rst2 = bd.Vertodo("select * from Medicos");
            ResultSet rst3 = bd.Vertodo("select * from Tratamiento");
            DefaultTableModel model = new DefaultTableModel(), model1 = new DefaultTableModel(), model2 = new DefaultTableModel();
            jtConsulta.setModel(model);
            jtTabla.setModel(model1);
            jtConsulta1.setModel(model2);
            model.setColumnIdentifiers(new Object[]{"Codigo del Paciente", "Nombre", "Apellido", "Edad", "Sexo", "Cedula", "Telefono", "Fecha de nacimiento", "Seguro", "Fecha del regristro"});
            model1.setColumnIdentifiers(new Object[]{"Codigo del Medico", "Nombre", "Apellido", "Fecha del registro", "Telefono", "Contraseña", "Categoria"});
            model2.setColumnIdentifiers(new Object[]{"Codigo del Tratamieno", "Nombre", "Medicameto", "Ciclo", "Dosis"});
            
            while(rs.next()){
            a1 = rs.getInt("Id_paciingre");
                
            }
            while(rst.next()){

                model.addRow(new Object[]{rst.getInt("Id_pacientes"), rst.getString("Nombre_pa"), rst.getString("Apellido"), rst.getString("Edad"), rst.getString("Sexo"), rst.getString("Cedula"), rst.getString("Telefono"), rst.getString("Fecha_nacimiento"), rst.getString("Seguro"), rst.getString("Fecha_registro")});

            }
            while(rst2.next()){

                model1.addRow(new Object[]{rst2.getInt("Id_medico"), rst2.getString("Nombre_me"), rst2.getString("Apellido"), rst2.getString("Fecha_registro"), rst2.getString("Telefono"), rst2.getString("Contrasena"), rst2.getString("Categoria")});

            }
            
            while(rst3.next()){

                model2.addRow(new Object[]{rst3.getInt("Id_Tratamiento"), rst3.getString("Nombre_tra"), rst3.getString("Medicamento"), rst3.getString("Ciclo"), rst3.getString("Dosis")});

            }
            
            
            a = a1 + 1;
            
        } catch(Exception e){
            
        } finally{
            bd.close();
        }
        
        jLabel3.setText(String.valueOf(a));
        
    }
    
    public void Buscar(){
            
            int a1=0;

            
            
        try {
            ResultSet rs1 = bd.Vertodo("select * from Pacientes_ingresados");
            while(rs1.next()){
                a1 = rs1.getInt("Id_paciingre");
                
            }
        } catch (SQLException ex) {
        }
        
        a = a1 + 1;
        jLabel3.setText(String.valueOf(a));
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdMedico = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtTabla = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jtxtBuscar1 = new javax.swing.JTextField();
        jbtBuscar1 = new javax.swing.JButton();
        jrbNombre1 = new javax.swing.JRadioButton();
        jrbCodigo1 = new javax.swing.JRadioButton();
        jbtMostrar1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jdPaciente = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jbtBuscar = new javax.swing.JButton();
        jrbNombre = new javax.swing.JRadioButton();
        jtxtBuscar = new javax.swing.JTextField();
        jrbCodigo = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtConsulta = new javax.swing.JTable();
        jbtMostrar = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jdTratamiento = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jbtBuscar2 = new javax.swing.JButton();
        jrbNombre2 = new javax.swing.JRadioButton();
        jtxtBuscar2 = new javax.swing.JTextField();
        jrbCodigo2 = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtConsulta1 = new javax.swing.JTable();
        jbtMostrar2 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        jdMedico.setTitle("Consulta Medicos");
        jdMedico.setMinimumSize(new java.awt.Dimension(930, 690));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel13.setText("Consultar medicos");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jtTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtTabla);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 819, -1));

        jButton7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Volver 1.png"))); // NOI18N
        jButton7.setText("Volver");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 630, 140, 50));
        jPanel3.add(jtxtBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 210, 30));

        jbtBuscar1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jbtBuscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        jbtBuscar1.setText("Buscar");
        jbtBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBuscar1ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 150, 50));

        jrbNombre1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jrbNombre1.setText("Nombre");
        jPanel3.add(jrbNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, -1, -1));

        jrbCodigo1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jrbCodigo1.setSelected(true);
        jrbCodigo1.setText("Codigo");
        jPanel3.add(jrbCodigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, -1, -1));

        jbtMostrar1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jbtMostrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mostrar.png"))); // NOI18N
        jbtMostrar1.setText("Mostrar Todo");
        jbtMostrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtMostrar1ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtMostrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 240, 50));

        jButton8.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Confirmar.png"))); // NOI18N
        jButton8.setText("Seleccionar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 109, 170, 50));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/textura.png"))); // NOI18N
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 690));

        javax.swing.GroupLayout jdMedicoLayout = new javax.swing.GroupLayout(jdMedico.getContentPane());
        jdMedico.getContentPane().setLayout(jdMedicoLayout);
        jdMedicoLayout.setHorizontalGroup(
            jdMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdMedicoLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jdMedicoLayout.setVerticalGroup(
            jdMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdMedicoLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jdPaciente.setTitle("Consulta Pacientes");
        jdPaciente.setMinimumSize(new java.awt.Dimension(950, 690));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Volver 1.png"))); // NOI18N
        jButton6.setText("Volver");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(672, 612, 140, 50));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel15.setText("Consultar Pacientes");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jbtBuscar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jbtBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        jbtBuscar.setText("Buscar");
        jbtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 160, 50));

        jrbNombre.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jrbNombre.setText("Nombre");
        jPanel2.add(jrbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, -1, -1));
        jPanel2.add(jtxtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 109, 210, 30));

        jrbCodigo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jrbCodigo.setSelected(true);
        jrbCodigo.setText("Codigo");
        jPanel2.add(jrbCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, -1, -1));

        jtConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtConsulta);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 819, -1));

        jbtMostrar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jbtMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mostrar.png"))); // NOI18N
        jbtMostrar.setText("Mostrar Todo");
        jbtMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtMostrarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 240, 50));

        jButton9.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Confirmar.png"))); // NOI18N
        jButton9.setText("Seleccionar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 180, 50));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/textura.png"))); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 690));

        javax.swing.GroupLayout jdPacienteLayout = new javax.swing.GroupLayout(jdPaciente.getContentPane());
        jdPaciente.getContentPane().setLayout(jdPacienteLayout);
        jdPacienteLayout.setHorizontalGroup(
            jdPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jdPacienteLayout.setVerticalGroup(
            jdPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
        );

        jdTratamiento.setMinimumSize(new java.awt.Dimension(950, 690));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Volver 1.png"))); // NOI18N
        jButton10.setText("Volver");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(672, 612, 140, 50));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel17.setText("Consultar Tratamiento");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jbtBuscar2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jbtBuscar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        jbtBuscar2.setText("Buscar");
        jbtBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBuscar2ActionPerformed(evt);
            }
        });
        jPanel4.add(jbtBuscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 160, 50));

        jrbNombre2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jrbNombre2.setText("Nombre");
        jPanel4.add(jrbNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, -1, -1));
        jPanel4.add(jtxtBuscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 109, 210, 30));

        jrbCodigo2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jrbCodigo2.setSelected(true);
        jrbCodigo2.setText("Codigo");
        jPanel4.add(jrbCodigo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, -1, -1));

        jtConsulta1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jtConsulta1);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 819, -1));

        jbtMostrar2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jbtMostrar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mostrar.png"))); // NOI18N
        jbtMostrar2.setText("Mostrar Todo");
        jbtMostrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtMostrar2ActionPerformed(evt);
            }
        });
        jPanel4.add(jbtMostrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 240, 50));

        jButton11.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Confirmar.png"))); // NOI18N
        jButton11.setText("Seleccionar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 190, 50));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/textura.png"))); // NOI18N
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 690));

        javax.swing.GroupLayout jdTratamientoLayout = new javax.swing.GroupLayout(jdTratamiento.getContentPane());
        jdTratamiento.getContentPane().setLayout(jdTratamientoLayout);
        jdTratamientoLayout.setHorizontalGroup(
            jdTratamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jdTratamientoLayout.setVerticalGroup(
            jdTratamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Registro Pacientes Ingresados");
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jLabel1.setText("Registro Pacientes Ingresados");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel2.setText("No. Pacientes Ingresados:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 96, -1, -1));

        jLabel3.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 86, 79, 50));

        jLabel4.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel4.setText("Nombre del paciente:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 196, -1, -1));

        jLabel5.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel5.setText("Tratamiento:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 259, -1, -1));

        jLabel6.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel6.setText("Nombre del doctor:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel7.setText("Causa:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 393, -1, -1));

        jLabel8.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel8.setText("Estado:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 445, -1, -1));

        jButton1.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 186, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 186, 137, 31));

        jButton2.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 249, -1, -1));

        jButton3.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 315, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 393, 221, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 445, 221, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 137, 31));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 315, 137, 31));

        jButton4.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar.png"))); // NOI18N
        jButton4.setText("Guardar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 541, -1, -1));

        jButton5.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cerrar.png"))); // NOI18N
        jButton5.setText("Cancelar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 541, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/textura.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        this.hide();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    //Boton para insertar el registro
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        try{
        
        String Codigo = String.valueOf(a);
        String nombrepa = jLabel9.getText();
        String nombremed = jLabel11.getText();
        String nombretra = jLabel10.getText();
        String causa = jTextField1.getText();
        String estado = jTextField2.getText();
        
        if(nombrepa.equals("") || nombremed.equals("") || nombretra.equals("") || causa.equals("") || estado.equals("")){
        
            JOptionPane.showMessageDialog(null, "Faltan datos por introducir!", "Sistema De Consultorio", JOptionPane.INFORMATION_MESSAGE);
            
        }else{
                
                try{
                    bd.Insert("insert into Pacientes_ingresados(id_paciingre, Nombre_pa, Nombre_tra, nombre_me, causa, estado)"
                            + "values ("+Codigo+", '"+nombrepa+"', '"+nombretra+"', '"+nombremed+"', '"+causa+"', '"+estado+"')");
                    
                    jLabel9.setText("");
                    jLabel10.setText("");
                    jLabel11.setText("");
                    jTextField1.setText("");
                    jTextField2.setText("");
                    Buscar();
                    
                     }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "No Se Agrego El Registro", "Sistema De Consultorio", JOptionPane.INFORMATION_MESSAGE);
                    } finally{
                        bd.close();
                    }
            }
        
            
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Faltan datos por introducir!", "Sistema De Consultorio", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        jdMedico.hide();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jbtBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBuscar1ActionPerformed

        String nombre = jtxtBuscar1.getText();

        if(jrbNombre1.isSelected() == false && jrbCodigo1.isSelected() == false){
            JOptionPane.showMessageDialog(null, "No a elegino ningun tipo a buscar", "Sistema De Consultorio", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if(jrbNombre1.isSelected() == true && jrbCodigo1.isSelected() == true){
                JOptionPane.showMessageDialog(null, "Solo puede sellecionar una sola opcion", "Sistema De Consultorio", JOptionPane.INFORMATION_MESSAGE);
            } else if(jrbNombre1.isSelected() == true){if(nombre.equals("")){
                JOptionPane.showMessageDialog(null, "No a escrito el nombre a buscar", "Sistema De Consultorio", JOptionPane.INFORMATION_MESSAGE);
            } else{
                char k = nombre.charAt(0);
                if(Character.isDigit(k)){
                    JOptionPane.showMessageDialog(null, "Solo Puede introducir Letras", "Sistema De Consultorio", JOptionPane.INFORMATION_MESSAGE);
                } else{

                    DefaultTableModel model = new DefaultTableModel();
                    jtTabla.setModel(model);
                    model.setColumnIdentifiers(new Object[]{"Codigo del Medico", "Nombre", "Apellido", "Fecha del registro", "Telefono", "Contraseña", "Categoria"});
                    try{
                        ResultSet rs = bd.Vertodo("select * from Medicos where Nombre like'"+nombre+"%'");

                        while(rs.next()){

                            model.addRow(new Object[]{rs.getInt("Id_medico"), rs.getString("Nombre_me"), rs.getString("Apellido"), rs.getString("Fecha_registro"), rs.getString("Telefono"), rs.getString("Contrasena"), rs.getString("Categoria")});

                        }

                    } catch(Exception e){

                    } finally{
                        bd.close();
                    }
                }
            }
        }else{
            if(nombre.equals("")){
                JOptionPane.showMessageDialog(null, "No a escrito el codigo a buscar", "Sistema De Consultorio", JOptionPane.INFORMATION_MESSAGE);
            } else {
                try{
                    int ho = Integer.parseInt(nombre);
                    if(ho > 0){
                        ResultSet rs = bd.Vertodo("select * from Medicos where Id_medico = "+nombre+"");
                        DefaultTableModel model = new DefaultTableModel();
                        jtTabla.setModel(model);
                        model.setColumnIdentifiers(new Object[]{"Codigo del Medico", "Nombre", "Apellido", "Fecha del registro", "Telefono", "Contraseña", "Categoria"});

                        while(rs.next()){

                            model.addRow(new Object[]{rs.getInt("Id_medico"), rs.getString("Nombre_me"), rs.getString("Apellido"), rs.getString("Fecha_registro"), rs.getString("Telefono"), rs.getString("Contrasena"), rs.getString("Categoria")});

                        }
                    }

                } catch(Exception e){

                    JOptionPane.showMessageDialog(null, "Solo puede introducir numeros", "Sistema De Consultorio", JOptionPane.INFORMATION_MESSAGE);

                } finally{
                    bd.close();
                }
            }
        }
        }
    }//GEN-LAST:event_jbtBuscar1ActionPerformed

    private void jbtMostrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtMostrar1ActionPerformed

        DefaultTableModel model = new DefaultTableModel();
        jtTabla.setModel(model);
        model.setColumnIdentifiers(new Object[]{"Codigo del Medico", "Nombre", "Apellido", "Fecha del registro", "Telefono", "Contraseña", "Categoria"});
        try{
            ResultSet rs = bd.Vertodo("select * from Medicos");

            while(rs.next()){

                model.addRow(new Object[]{rs.getInt("Id_medico"), rs.getString("Nombre_me"), rs.getString("Apellido"), rs.getString("Fecha_registro"), rs.getString("Telefono"), rs.getString("Contrasena"), rs.getString("Categoria")});

            }

        } catch(Exception e){

        } finally{
            bd.close();
        }
    }//GEN-LAST:event_jbtMostrar1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        fila1 = jtTabla.getSelectedRow();
        String at = "";

        try{
            if(fila1==-1){
                JOptionPane.showMessageDialog(null, "Debe de seleccionar un registro", "Advertencia", JOptionPane.WARNING_MESSAGE);
            } else {
                at = jtTabla.getValueAt(fila1, 1).toString();
                jdMedico.hide();
                
            }
            this.come = 1;
            jLabel11.setText(at);

        }catch (Exception ex) {

        }

        fila1 = 0;

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        jdPaciente.hide();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jbtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBuscarActionPerformed

        String nombre = jtxtBuscar.getText();

        if(jrbNombre.isSelected() == false && jrbCodigo.isSelected() == false){
            JOptionPane.showMessageDialog(null, "No a elegino ningun tipo a buscar", "Sistema De Consultorio", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if(jrbNombre.isSelected() == true && jrbCodigo.isSelected() == true){
                JOptionPane.showMessageDialog(null, "Solo puede sellecionar una sola opcion", "Sistema De Consultorio", JOptionPane.INFORMATION_MESSAGE);
            } else if(jrbNombre.isSelected() == true){if(nombre.equals("")){
                JOptionPane.showMessageDialog(null, "No a escrito el nombre a buscar", "Sistema De Consultorio", JOptionPane.INFORMATION_MESSAGE);
            } else{
                char k = nombre.charAt(0);
                if(Character.isDigit(k)){
                    JOptionPane.showMessageDialog(null, "Solo Puede introducir Letras", "Sistema De Consultorio", JOptionPane.INFORMATION_MESSAGE);
                } else{

                    try{

                        ResultSet rs = bd.Vertodo("select * from Pacientes where Nombre like'"+nombre+"%'");
                        DefaultTableModel model = new DefaultTableModel();
                        jtConsulta.setModel(model);
                        model.setColumnIdentifiers(new Object[]{"Codigo del Paciente", "Nombre", "Apellido", "Edad", "Sexo", "Cedula", "Telefono", "Fecha de nacimiento", "Seguro", "Fecha del regristro"});

                        while(rs.next()){

                            model.addRow(new Object[]{rs.getInt("Id_pacientes"), rs.getString("Nombre_pa"), rs.getString("Apellido"), rs.getString("Edad"), rs.getString("Sexo"), rs.getString("Cedula"), rs.getString("Telefono"), rs.getString("Fecha_nacimiento"), rs.getString("Seguro"), rs.getString("Fecha_registro")});

                        }

                    } catch(Exception e){

                    } finally{
                        bd.close();
                    }
                }
            }
        }else{
            if(nombre.equals("")){
                JOptionPane.showMessageDialog(null, "No a escrito el codigo a buscar", "Sistema De Consultorio", JOptionPane.INFORMATION_MESSAGE);
            } else {
                try{
                    int ho = Integer.parseInt(nombre);
                    if(ho > 0){
                        ResultSet rs = bd.Vertodo("select * from Pacientes where Id_pacientes = "+nombre+"");
                        DefaultTableModel model = new DefaultTableModel();
                        jtConsulta.setModel(model);
                        model.setColumnIdentifiers(new Object[]{"Codigo del Paciente", "Nombre", "Apellido", "Edad", "Sexo", "Cedula", "Telefono", "Fecha de nacimiento", "Seguro", "Fecha del regristro"});

                        while(rs.next()){

                            model.addRow(new Object[]{rs.getInt("Id_pacientes"), rs.getString("Nombre_pa"), rs.getString("Apellido"), rs.getString("Edad"), rs.getString("Sexo"), rs.getString("Cedula"), rs.getString("Telefono"), rs.getString("Fecha_nacimiento"), rs.getString("Seguro"), rs.getString("Fecha_registro")});

                        }
                    }

                } catch(Exception e){

                    JOptionPane.showMessageDialog(null, "Solo puede introducir numeros", "Sistema De Consultorio", JOptionPane.INFORMATION_MESSAGE);

                } finally{
                    bd.close();
                }
            }
        }
        }
    }//GEN-LAST:event_jbtBuscarActionPerformed

    private void jbtMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtMostrarActionPerformed

        DefaultTableModel model = new DefaultTableModel();
        jtConsulta.setModel(model);
        model.setColumnIdentifiers(new Object[]{"Codigo del Paciente", "Nombre", "Apellido", "Edad", "Sexo", "Cedula", "Telefono", "Fecha de nacimiento", "Seguro", "Fecha del regristro"});
        try{
            ResultSet rs = bd.Vertodo("select * from Pacientes");

            while(rs.next()){

                model.addRow(new Object[]{rs.getInt("Id_pacientes"), rs.getString("Nombre_pa"), rs.getString("Apellido"), rs.getString("Edad"), rs.getString("Sexo"), rs.getString("Cedula"), rs.getString("Telefono"), rs.getString("Fecha_nacimiento"), rs.getString("Seguro"), rs.getString("Fecha_registro")});

            }

        } catch(Exception e){

        } finally{
            bd.close();
        }
    }//GEN-LAST:event_jbtMostrarActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        fila1 = jtConsulta.getSelectedRow();
        String at = "";

        try{
            if(fila1==-1){
                JOptionPane.showMessageDialog(null, "Debe de seleccionar un registro", "Advertencia", JOptionPane.WARNING_MESSAGE);
            } else {
                at = jtConsulta.getValueAt(fila1, 1).toString();
                jdPaciente.hide();
                
            }
            this.copa = 1;
            jLabel9.setText(at);

        }catch (Exception ex) {

        }

        fila1 = 0;

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jdPaciente.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jdMedico.show();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jdTratamiento.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        jdTratamiento.hide();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jbtBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBuscar2ActionPerformed
        
         String nombre = jtxtBuscar2.getText();

        if(jrbNombre2.isSelected() == false && jrbCodigo2.isSelected() == false){
            JOptionPane.showMessageDialog(null, "No a elegino ningun tipo a buscar", "Sistema de Consultorio", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if(jrbNombre2.isSelected() == true && jrbCodigo2.isSelected() == true){
                JOptionPane.showMessageDialog(null, "Solo puede sellecionar una sola opcion", "Sistema de Consultorio", JOptionPane.INFORMATION_MESSAGE);
            } else if(jrbNombre2.isSelected() == true){if(nombre.equals("")){
                JOptionPane.showMessageDialog(null, "No a escrito el nombre a buscar", "Sistema de Consultorio", JOptionPane.INFORMATION_MESSAGE);
            } else{
                char k = nombre.charAt(0);
                if(Character.isDigit(k)){
                    JOptionPane.showMessageDialog(null, "Solo Puede introducir Letras", "Sistema de Consultorio", JOptionPane.INFORMATION_MESSAGE);
                } else{

                    try{

                        ResultSet rs = bd.Vertodo("select * from tratamiento where Nombre like'"+nombre+"%'");
                        DefaultTableModel model = new DefaultTableModel();
                        jtConsulta1.setModel(model);
                        model.setColumnIdentifiers(new Object[]{"Codigo del Tratamieno", "Nombre", "Medicameto", "Ciclo", "Dosis"});
            
                        while(rs.next()){

                            model.addRow(new Object[]{rs.getInt("Id_Tratamiento"), rs.getString("Nombre"), rs.getString("Medicamento"), rs.getString("Ciclo"), rs.getString("Dosis")});

                        }

                    } catch(Exception e){

                    } finally{
                        bd.close();
                    }
                }
            }
        }else{
            if(nombre.equals("")){
                JOptionPane.showMessageDialog(null, "No a escrito el codigo a buscar", "Sistema de Consultorio", JOptionPane.INFORMATION_MESSAGE);
            } else {
                try{
                    int ho = Integer.parseInt(nombre);
                    if(ho > 0){
                        ResultSet rs = bd.Vertodo("select * from tratamiento where Id_tratamiento = "+nombre+"");
                        DefaultTableModel model = new DefaultTableModel();
                        jtConsulta1.setModel(model);
                        model.setColumnIdentifiers(new Object[]{"Codigo del Tratamieno", "Nombre", "Medicameto", "Ciclo", "Dosis"});
            
                        while(rs.next()){

                            model.addRow(new Object[]{rs.getInt("Id_Tratamiento"), rs.getString("Nombre"), rs.getString("Medicamento"), rs.getString("Ciclo"), rs.getString("Dosis")});

                        }
                    }

                } catch(Exception e){

                    JOptionPane.showMessageDialog(null, "Solo puede introducir numeros", "Sistema De Consultorio", JOptionPane.INFORMATION_MESSAGE);

                } finally{
                    bd.close();
                }
            }
        }
        }
        
    }//GEN-LAST:event_jbtBuscar2ActionPerformed

    private void jbtMostrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtMostrar2ActionPerformed
        
        DefaultTableModel model = new DefaultTableModel();
        jtConsulta1.setModel(model);
        model.setColumnIdentifiers(new Object[]{"Codigo del Tratamieno", "Nombre", "Medicameto", "Ciclo", "Dosis"});
        try{
            ResultSet rs = bd.Vertodo("select * from tratamiento");

            while(rs.next()){

                model.addRow(new Object[]{rs.getInt("Id_Tratamiento"), rs.getString("Nombre"), rs.getString("Medicamento"), rs.getString("Ciclo"), rs.getString("Dosis")});

            }

        } catch(Exception e){

        } finally{
            bd.close();
        }
        
    }//GEN-LAST:event_jbtMostrar2ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        
        fila1 = jtConsulta1.getSelectedRow();
        String at = "";

        try{
            if(fila1==-1){
                JOptionPane.showMessageDialog(null, "Debe de seleccionar un registro", "Advertencia", JOptionPane.WARNING_MESSAGE);
            } else {
                at = jtConsulta1.getValueAt(fila1, 1).toString();
                jdTratamiento.hide();
                
            }
            this.cotra = 1;
            jLabel10.setText(at);

        }catch (Exception ex) {

        }

        fila1 = 0;
        
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pacientesingre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pacientesingre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pacientesingre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pacientesingre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pacientesingre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton jbtBuscar;
    private javax.swing.JButton jbtBuscar1;
    private javax.swing.JButton jbtBuscar2;
    private javax.swing.JButton jbtMostrar;
    private javax.swing.JButton jbtMostrar1;
    private javax.swing.JButton jbtMostrar2;
    private javax.swing.JDialog jdMedico;
    private javax.swing.JDialog jdPaciente;
    private javax.swing.JDialog jdTratamiento;
    private javax.swing.JRadioButton jrbCodigo;
    private javax.swing.JRadioButton jrbCodigo1;
    private javax.swing.JRadioButton jrbCodigo2;
    private javax.swing.JRadioButton jrbNombre;
    private javax.swing.JRadioButton jrbNombre1;
    private javax.swing.JRadioButton jrbNombre2;
    private javax.swing.JTable jtConsulta;
    private javax.swing.JTable jtConsulta1;
    private javax.swing.JTable jtTabla;
    public static javax.swing.JTextField jtxtBuscar;
    public static javax.swing.JTextField jtxtBuscar1;
    public static javax.swing.JTextField jtxtBuscar2;
    // End of variables declaration//GEN-END:variables

    Conectar_Mysql bd = new Conectar_Mysql();

}
